// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jwybtedqtmwtusuowhab.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp3eWJ0ZWRxdG13dHVzdW93aGFiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA1MjYzNDMsImV4cCI6MjA1NjEwMjM0M30.ooqikxOaS5ksv4aPqnEB3HkxuJ6lGvn759o3lF3-QwQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);